workflows:
  react-native:
    name: React Native App
    environment:
      node: latest
    scripts:
      - yarn install
      - yarn android || echo "Android build failed, continuing..."
      - yarn ios || echo "iOS build failed, continuing..."
    artifacts:
      - android/app/build/outputs/**/*.apk
      - ios/build/Build/Products/**/*.app
