workflows:
  react-native:
    name: React Native App
    environment:
      android_signing:
        - keystore_reference
      vars:
       CM_KEYSTORE_PATH: bXktdXBsb2FkLWtleS5rZXlzdG9yZQ==
       CM_KEYSTORE_PASSWORD: YW5kcm9pZA==
       CM_KEY_ALIAS: bXkta2V5LWFsaWFz
       CM_KEY_PASSWORD: YW5kcm9pZA==
      node: latest
    scripts:
      - yarn install
      - echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
      - |
         # build Android
         cd android
         ./gradlew assembleRelease 
    artifacts:
      - android/app/build/outputs/**/*.apk
