workflows:
  react-native:
    name: React Native App
    environment:
      android_signing:
        - keystore_reference
      vars:
        JAVA_HOME: "/usr/lib/jvm/zulu-17.jdk/Contents/Home"
      node: latest
    scripts:
      - yarn install
      - echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
      - |
         # Verify Java version
         java -version

         # build Android
         cd android
         ./gradlew assembleRelease 
    artifacts:
      - android/app/build/outputs/**/*.apk
